
  CREATE TABLE "HR"."LIBRARY_BOOK" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"BOOK_TYPE" VARCHAR2(20 BYTE), 
	"BOOK_NAME" VARCHAR2(120 BYTE), 
	"TOTAL_NAME" VARCHAR2(120 BYTE), 
	"AUTHOR" VARCHAR2(100 BYTE), 
	"BOOK_COMPANY" VARCHAR2(120 BYTE), 
	"BOOK_YEAR" NUMBER, 
	"BOOK_PAGE" VARCHAR2(20 BYTE), 
	"ISBN" VARCHAR2(120 BYTE), 
	"PRICE" NUMBER, 
	"BOOK_CNT" NUMBER, 
	"REGIDATE" DATE, 
	 CONSTRAINT "LIBRARY_BOOK_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "HR"."LIBRARY_BOOK"."BOOK_TYPE" IS '자료유형';
   COMMENT ON COLUMN "HR"."LIBRARY_BOOK"."BOOK_NAME" IS '도서명';
   COMMENT ON COLUMN "HR"."LIBRARY_BOOK"."TOTAL_NAME" IS '총서명';
   COMMENT ON COLUMN "HR"."LIBRARY_BOOK"."AUTHOR" IS '저자';
   COMMENT ON COLUMN "HR"."LIBRARY_BOOK"."BOOK_COMPANY" IS '출판사';
   COMMENT ON COLUMN "HR"."LIBRARY_BOOK"."BOOK_YEAR" IS '출판년도';
   COMMENT ON COLUMN "HR"."LIBRARY_BOOK"."BOOK_PAGE" IS '판차/페이지';
   COMMENT ON COLUMN "HR"."LIBRARY_BOOK"."ISBN" IS 'ISBN';
   COMMENT ON COLUMN "HR"."LIBRARY_BOOK"."PRICE" IS '가격';
   COMMENT ON COLUMN "HR"."LIBRARY_BOOK"."BOOK_CNT" IS '수량';
   COMMENT ON COLUMN "HR"."LIBRARY_BOOK"."REGIDATE" IS '등록일자';

  CREATE OR REPLACE TRIGGER "HR"."LIBRARY_BOOK_TRG" 
BEFORE INSERT ON LIBRARY_BOOK 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT LIBRARY_BOOK_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HR"."LIBRARY_BOOK_TRG" ENABLE;