
  CREATE TABLE "HR"."LIBRARY_BOOK_RESERVATION" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"BOOK_ID" NUMBER, 
	"ACCOUNT_ID" NUMBER, 
	"BOOK_CNT" NUMBER, 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"IP" VARCHAR2(129 BYTE), 
	 CONSTRAINT "LIBRARY_BOOK_RESERVATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "HR"."LIBRARY_BOOK_RESERVATION"."BOOK_ID" IS '도서 일련번호';
   COMMENT ON COLUMN "HR"."LIBRARY_BOOK_RESERVATION"."ACCOUNT_ID" IS '계정 일련번호';
   COMMENT ON COLUMN "HR"."LIBRARY_BOOK_RESERVATION"."BOOK_CNT" IS '대여갯수';
   COMMENT ON COLUMN "HR"."LIBRARY_BOOK_RESERVATION"."START_DATE" IS '대여일자';
   COMMENT ON COLUMN "HR"."LIBRARY_BOOK_RESERVATION"."END_DATE" IS '반납일자';

  CREATE OR REPLACE TRIGGER "HR"."LIBRARY_BOOK_RESERVATION_TRG" 
BEFORE INSERT ON LIBRARY_BOOK_RESERVATION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT LIBRARY_BOOK_RESERVATION_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HR"."LIBRARY_BOOK_RESERVATION_TRG" ENABLE;

