
  CREATE TABLE "HR"."LIBRARY_BOOK_COLLECTION_INFO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"BILLING_NUMBER" VARCHAR2(20 BYTE), 
	"COLLECTION" VARCHAR2(20 BYTE), 
	"REGISTER_NUMBER" VARCHAR2(20 BYTE), 
	"BOOK_ID" NUMBER, 
	 CONSTRAINT "LIBRARY_BOOK_COLLECTION_IN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "HR"."LIBRARY_BOOK_COLLECTION_INFO"."BILLING_NUMBER" IS '청구기호';
   COMMENT ON COLUMN "HR"."LIBRARY_BOOK_COLLECTION_INFO"."COLLECTION" IS '소장처';
   COMMENT ON COLUMN "HR"."LIBRARY_BOOK_COLLECTION_INFO"."REGISTER_NUMBER" IS '등록번호';
   COMMENT ON COLUMN "HR"."LIBRARY_BOOK_COLLECTION_INFO"."BOOK_ID" IS '책번호';

  CREATE OR REPLACE TRIGGER "HR"."LIBRARY_BOOK_COLLECTION_INFO_" 
BEFORE INSERT ON LIBRARY_BOOK_COLLECTION_INFO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT LIBRARY_BOOK_COLLECTION_INFO_1.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HR"."LIBRARY_BOOK_COLLECTION_INFO_" ENABLE;

