  CREATE TABLE "HR"."LIBRARY_ACCOUNT" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"USR_ID" VARCHAR2(100 BYTE), 
	"PASSWD" VARCHAR2(150 BYTE), 
	"MEMBER_ID" NUMBER, 
	"REGIDATE" DATE, 
	"AUTHORIZE" VARCHAR2(20 BYTE), 
	 CONSTRAINT "LIBRARY_MEMBER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "HR"."LIBRARY_ACCOUNT"."AUTHORIZE" IS '권한';

  CREATE OR REPLACE TRIGGER "HR"."LIBRARY_ACCOUNT_TRG" 
BEFORE INSERT ON LIBRARY_ACCOUNT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HR"."LIBRARY_ACCOUNT_TRG" ENABLE;